theme = "docs-v1"
baseURL = "/"
languageCode = "en-us"
title = "Documentation"
minify = true
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true
pygmentsUseClasses=true
disableKinds = ["RSS", "sitemap"]
[taxonomies]
  tag = "tags"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
